=== bondua2/coursera-test/site/xml/mypl.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="playlist">
<xs:complexType>
	<xs:sequence>
		<xs:element name="title" type="xs:string" minOccurs="0" />
		<xs:element name="trackList">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="track" type="trackType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="extension" type="extenType"/>
			<!--<complexType>
				<xs:sequence>
					<xs:element name="item">
						<xs:complexType>
						
							<xs:attribute name="tid" type="xs:srting"/>
						
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>-->
	</xs:sequence>
	<xs:attribute name="version" type="xs:string" use="optional"/>
</xs:complexType>
</xs:element>

<!-- Type definision-->
<xs:complexType name="trackType">
	<xs:sequence>
	
		<xs:element name="location" type="xs:anyURI" minOccurs="1"/>
		
		<xs:element name="title" type="xs:string"/>
		<xs:element name="album" type="xs:string"/>
		<xs:element name="extension">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="id" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="application" type="xs:anyURI" use="optional"/>
			</xs:complexType>
		</xs:element>
	
	</xs:sequence>
	
<xs:complexType name="extenType">
	<xs:sequence>
		<xs:element name="item">
			<xs:complexType>
				<xs:attribute name="tid" type="xs:string" use="required"/>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

</xs:complexType>

</xs:schema>

=== bondua2/coursera-test/site/xml/mypl.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--<playlist
		xmlns:vls="http://www.videolan.org/vlc/playlist/ns/0/"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:targetNamespace="http://xspf.org/ns/0/"
		xmlns="http://xspf.org/ns/0/"
		xsi:schemaLocation="mypl.xsd"
		version="1">-->
<playlist
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="mypl.xsd"
		xmlns:vlc="http://www.videolan.org/vlc/playlist/ns/0/"
		version="1">
	
	<title></title>
		<trackList>
			<track>
				
				<location></location>
				<title></title>
				<album></album>
				<extension application="http://www.videolan.org/vlc/playlist/0">
					<vlc:id>1</vlc:id>
				</extension>
			</track>
		</trackList>
		
		<extension>
			<vlc:item tid="0"/>
		</extension>
</playlist>
